language: cpp
compiler:
  - gcc

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
    #- secure: "*my secured token for coverity"

addons:
    coverity_scan:
      project:
        name: "iotivity-clone"
      notification_email: phg@graniteriverlabs.com
      build_command_prepend: ""
      build_command: "scons TARGET_ARCH=x86"
      branch_pattern: master

